spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: ${DB_HOST}
    username: ${DB_USER}
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true